<?php

return [
    'COMMERCIAL' => 'Commercial',
    'RESIDENTIAL' => 'Residential',
    'ACTIVE' => 'Active',
    'INACTIVE' => 'Inactive',
    'ON_HOLD' => 'On-Hold',
    'COMPLETE' => 'Complete',
    'CANCELLED' => 'Cancelled',
    'PENDING' => 'Pending',
    'RESCHEDULED' => 'Re-scheduled',
    'PER_SERVICE' => 'Per service',
    'MONTHLY' => 'Monthly',
    'INITIAL_MONTHLY' => 'Initial monthly',
    'DUE_AT_SIGNUP' => 'Due at signup',
    'TWO_PAYMENTS' => 'Two payments',
    'INSTALLMENTS' => 'Installments',
    'PAID' => 'Paid',
    'UNPAID' => 'Unpaid',
    'NOT_SENT' => 'Not sent',
    'SENT' => 'Sent',
    'DUE' => 'Due',
    'PAST_DUE' => 'Past due',
    'COLLECTIONS' => 'Collections',
    'IN_COLLECTIONS' => 'In collections',
    'REGULAR' => 'Regular',
    'DISCOUNT' => 'Discount',
    'CREDIT' => 'Credit',
    /**
     * An adjustment made by the system.
     *
     * These items should not be included when calculating an invoice's amount due.
     */
    'INTERNAL_ADJUSTMENT' => 'Adjustment',
    'POINTS' => 'Points',
    'SALE' => 'Sale',
    'WEEKLY' => 'Weekly',
    'BI_WEEKLY' => 'Bi-weekly',
    'TRI_WEEKLY' => 'Tri-weekly',
    'MONTHLY' => 'Monthly',
    'BI_MONTHLY' => 'Bi-monthly',
    'TWICE_PER_MONTH' => 'Twice Per Month',
    'HEXA_WEEKLY' => 'Every Six Weeks',
    'QUARTERLY' => 'Quarterly',
    'SEMI_ANNUALLY' => 'Semi-annually',
    'ANNUALLY' => 'Annually',
    'TRI_ANNUALLY' => 'Tri-Annually',
    'ONE_TIME' => 'One-Time',
    'CUSTOM' => 'Custom',
    'CUSTOM_MANUAL' => 'Custom (Manual)',
    'CKEDITOR_UPLOAD_DIR' => '/files/ckeditor',
    'VERIFICATION' => 'verification',
    'INVOICES' => 'invoices',
    'SUMMARY' => 'summary',
    'CONTRACT' => 'contract',
    'CUSTOMER_USER' => 'customer_user',
    'REMOTE_COMPLETION' => 'remote_completion',
    'INTERNAL_PATH' => storage_path('app/public'),
    'S3_INTERNAL_PATH' => 'https://pocomos-dev.s3.amazonaws.com/',
    'CUSTOMER_PORTAL_LINK_EXPIRY' => '3',//Month
    'INITIAL' => 'Initial',
    'ROLE_TECH_RESTRICTED' => false,
    'ROLE_OWNER' => true,
    'LEAD' => 'Lead',
    'NOT_HOME' => 'Not Home',
    'NOT_INTERESTED' => 'Not Interested',
    'CUSTOMER' => 'Customer',
    'MONITOR' => 'Monitor',
    'NOT_KNOCK' => 'Do Not Knock',
    'MOBILE' => 'Mobile',
    'HOME' => 'Home',
    'FAX' => 'Fax',
    'TALK' => 'Talk',
    'KNOCK' => 'Knock',
    'OFFICE' => 'Office',
    'SENDER' => 'Sender',
    'PAST_DUE_AFTER_DAYS' => 28,
    'ACTIVE_CONTEXT_KEY' => 'current_contract_context',
    'DEFAULT_CURRENCY' => '$',
    'CARD_ACCOUNT' => 'CardAccount',
    'DECLINED' => 'Declened',
    'APPROVED' => 'Approved',
    'ROLE_TECHNICIAN' => false,
    'ROLE_DASHBOARD_READ' => false,
    'CUSTOMER_REMOTE_COMPLETION_EDIT' => 'https://mypocomos.net/customer/remote/',
    'ACTIVE_OFFICE_ID' => 'current_office_id',
    'ACTIVE_OFFICE_USER_ID' => 'current_office_user_id',
    'HARD' => 'Hard',
    'HARD_CONFIRMED' => 'Hard-scheduled, Confirmed',
    'CONFIRMED' => 'Confirmed',
    'JOB_CONFIRMED' => 'Job Confirmed to Route',
    'PREVIOUS_LOGGEDIN_USER' => 'previous_loggedin_user',
    'PREVIOUS_USER_OFFICE_ID' => 'previous_user_office_id',
    'TWILLIO_NUMBER' => '+14094074706',
    'ACTIVE_THEME_KEY' => 'active_theme_key',
    'VERIFIED_EMAIL' => 'verifiedEmail',
    'DEFAULT_PRICE' => 20,
    'phoneNumberPrice' => 300,
    'FLAT' => 'Flat',
    'PERCENTAGE' => 'Percentage',
    'SUCCESS' => 'Success',
    'FAILED' => 'Failed',
    'DATE_ATOM' => 'Y-m-d\TH:i:sP',
    'LEADS' => 'Leads',
    'METHOD_ACH' => 'Method ach',
    'METHOD_CARD' => 'Method card',
    'UNSIGNED' => 'Unsigned',
    'REDIRECT_URL' => 'http://15.206.7.200/pocomos-admin/app',
    'DEFAULT_PAGE' => 1,
    "DEFAULT_PER_PAGE" => 10,
    "DEFAULT_OFFSET" => 0,
    'CUSTOMER_REMOTE_COMPLETION_URL' => '/pocomos-admin/app/customer/finalize-agreement/',
    'RECRUIT_REMOTE_COMPLETION_URL' => '/pocomos-admin/app/recruit/finalize/',
    'API_BASE_URL' => 'http://15.206.7.200/pocomos-backend/api/',
    'LUNCH' => 'Lunch',
    'DYNAMIC' => 'Dynamic',
    'RESERVED' => 'Reserved',
    // Customer emails
    'BILLING_SUMMARY_PAID' => 'Billing Summary (Paid)',
    'BILLING_SUMMARY_UNPAID' => 'Billing Summary (Unpaid)',
    'JOB_COMPLETE_INVOICE' => 'Job Complete (Invoice)',
    'JOB_COMPLETE_SERVICE_RECORD' => 'Job Complete (Service Record)',
    'JOB_CONFIRMED' => 'Job Confirmed to Route',
    'JOB_RESCHEDULED' => 'Job Re-scheduled',
    'VERIFY_ADDRESS' => 'Verify Email Address',
    'WELCOME_EMAIL' => 'Welcome Email',
    'REMOTE_CUSTOMER_COMPLETION' => 'Remote Customer Completion',
    'FORM_LETTER' => 'Form Letter',
    'CUSTOMER_USER_SETUP' => 'Customer Portal Setup',
    'RESEND_INVOICES' => 'Resend Invoices',
    'BILL' => 'Bill',

    // Employee emails
    'ASSIGNED_ALERT' => 'Alert Assigned',
    'NOTIFICATION' => 'Notification',

    // Recruit emails
    'RECRUIT_W9' => 'Recruit W9',
    'RECRUIT_AGREEMENT' => 'Recruit Agreement',
    'RECRUIT_REMOTE_COMPLETION' => 'Remote Recruit Completion',
    // Misc emails
    'CUSTOMER_EXPORT' => 'Customer Export',
    'PASSWORD_RESET' => 'Password Reset',
    // Send customer file by email
    'CUSTOMER_FILE' => 'Customer File',

    //Termite inspection
    'TERMITE_INSPECTION_COMPLETE' => 'Termite Inspection Complete',
    //Lead emails
    'LEAD_FORM_LETTER' => 'Lead Form Letter',
    'ESTIMATE_FORM_LETTER' => 'Estimate Form Letter',
    'AUTOMATE_EMAIL_REPORT' => 'Automate Email Report',
    // Inbound sms email type
    'INBOUND_SMS_EMAIL_TYPE' => 'Inbound SMS email Type',
    'ZIFT_SANDBOX_URL' => 'https://sandbox-secure.zift.io/gates/xurl?',
    'FRONTEND_URL' => 'http://15.206.7.200/pocomos-admin',
    'PDF_TYPES' => ['Invoice', 'Billing Summary', 'Service Record', 'Docusend', 'Estimate']
];
