<?php

return [
    # Writable roles automatically inherit read ability
    'ROLE_CUSTOMER_WRITE' =>    [ "ROLE_CUSTOMER_READ", "ROLE_CUSTOMER_CREATE", "ROLE_CUSTOMER_SHOW" , "ROLE_AGREEMENT_MANAGER", "ROLE_EDIT_AGREEMENT","ROLE_VIEW_AGREEMENT","ROLE_ARRANGE_ORDER_AGREEMENT","ROLE_FULL_AGREEMENT", "ROLE_VIEW_PEST_PRODUCT","ROLE_ARRANGE_ORDER_PEST_PRODUCT", "ROLE_FULL_PEST_PRODUCT"],
    'ROLE_CUSTOMER_CREATE' =>   ["ROLE_CUSTOMER_READ"],   # ROLE_CUSTOMER_CREATE is a special role for salespeople
    'ROLE_USER_WRITE' =>        ["ROLE_USER_READ"],
    'ROLE_ROUTE_WRITE' =>       ["ROLE_ROUTE_PROCESS" ],
    'ROLE_ROUTE_VIEW' =>        ["ROLE_ROUTE_READ"],
    'ROLE_ROUTE_PROCESS' =>     ["ROLE_ROUTE_READ"],
    'ROLE_COMPANY_WRITE' =>     ["ROLE_COMPANY_READ"],    # Administrator level Office
    'ROLE_OFFICE_WRITE' =>      ["ROLE_OFFICE_READ"],     # Company level Office
    'ROLE_DASHBOARD_WRITE' =>   ["ROLE_DASHBOARD_READ"],
    'ROLE_AGREEMENT_WRITE' =>   ["ROLE_AGREEMENT_READ"],
    'ROLE_SALES_ALERT_CONFIG_WRITE' => ["ROLE_SALES_ALERT_CONFIG_READ"],
    'ROLE_LEAD_WRITE' =>        ["ROLE_LEAD_READ"],
    'ROLE_CUSTOMFIELD_WRITE' => ["ROLE_CUSTOMFIELD_READ"],
    'ROLE_SALES_STATUS_WRITE' => ["ROLE_SALES_STATUS_READ"],
    'ROLE_ACCOUNT_CREATE' =>    ["ROLE_ACCOUNT_READ"],
    'ROLE_ACCOUNT_WRITE' =>     ["ROLE_ACCOUNT_CREATE"],
    'ROLE_PHONE_WRITE' =>       ["ROLE_PHONE_READ"],
    'ROLE_QR_CODE_BATCH_WRITE' => ["ROLE_QR_CODE_BATCH_READ"],
    'ROLE_QR_CODE_SCAN_WRITE' => ["ROLE_QR_CODE_SCAN_READ"],
    'ROLE_SUPPRESS_SALESPERSON_VIEW' => ["ROLE_SUPPRESS_SALESPERSON_VIEW"],
    'ROLE_PAYMENT_BULK' =>      ["ROLE_PAYMENT_CHARGE", "ROLE_PAYMENT_CANCEL", "ROLE_PAYMENT_FORM_LETTER", "ROLE_PAYMENT_SMS", "ROLE_PAYMENT_RESEND_EMAIL" ],
    'ROLE_ROUTE_BULK_COMPLETE' => ["ROLE_ROUTE_BULK_COMPLETE"],
    'ROLE_ROUTE_BULK_CONFIRM' =>  ["ROLE_ROUTE_BULK_CONFIRM"],
    'ROLE_STATUS_REASON_WRITE' => ["ROLE_STATUS_REASON_READ"],
    'ROLE_HISTORY_READ' =>        ["ROLE_HISTORY_READ"],
    'ROLE_TAXCODES_EDIT' =>       ["ROLE_TAXCODES_EDIT"],
    'ROLE_ZIPCODES_EDIT' =>       ["ROLE_ZIPCODES_EDIT"],
    'ROLE_CHANGE_SERVICE_PRICE' => ["ROLE_CHANGE_SERVICE_PRICE"],
    'ROLE_RECEIVE_CUSTOM_CONTRACT_ENDING_NOTIFICATION' => ["ROLE_RECEIVE_CUSTOM_CONTRACT_ENDING_NOTIFICATION"],

    'ROLE_RECRUIT_STATUS_WRITE' => ["ROLE_RECRUIT_STATUS_READ"],
    'ROLE_RECRUIT_CREATE' => ["ROLE_RECRUIT_READ"],
    'ROLE_RECRUIT_WRITE' => ["ROLE_RECRUIT_CREATE"],
    'ROLE_RECRUIT_OFFICE_WRITE' => ["ROLE_RECRUIT_OFFICE_READ"],
    'ROLE_RECRUIT_AGREEMENT_WRITE' => ["ROLE_RECRUIT_AGREEMENT_READ"],
    'ROLE_RECRUIT_CUSTOM_FIELD_WRITE' => ["ROLE_RECRUIT_CUSTOM_FIELD_READ"],

    'ROLE_RECRUITER' => ["ROLE_USER", "ROLE_RECRUIT_CREATE", "ROLE_RECRUIT_STATUS_READ", "ROLE_RECRUIT_OFFICE_READ", "ROLE_RECRUIT_AGREEMENT_READ", "ROLE_RECRUIT_CUSTOM_FIELD_READ" ],
    'ROLE_RECRUIT_MASTER_CONFIG_WRITE' => ["ROLE_RECRUIT_CONFIG_WRITE" ],
    'ROLE_RECRUIT_CONFIG_WRITE' => ["ROLE_RECRUIT_STATUS_WRITE", "ROLE_RECRUIT_OFFICE_WRITE", "ROLE_RECRUIT_AGREEMENT_WRITE", "ROLE_RECRUIT_CUSTOM_FIELD_WRITE" ],
    'ROLE_RECRUIT' => ["ROLE_USER", "ROLE_RECRUIT_AGREEMENT_READ" ],

    'ROLE_REPORT_COMPARISON' => ["ROLE_REPORT_COMPARISON_DATA"],

    'ROLE_COMPANY_RECORD_WRITE' => ["ROLE_COMPANY_RECORD_READ"],

    'ROLE_MOVE_JOBS_TO_PAST' => ["ROLE_MOVE_JOBS_TO_PAST"],
    'ROLE_CUSTOMER_SHOW' =>    ["ROLE_CUSTOMER_SHOW"],  # Allowed to see full customer detail
    'ROLE_CUSTOMER_ACTIONS' => ["ROLE_CUSTOMER_ACTIONS"],
    'ROLE_JOB_COMPLETE' =>     ["ROLE_JOB_COMPLETE"],
    'ROLE_BULK_COLLECTIONS' => ["ROLE_BULK_COLLECTIONS"],
    'ROLE_CONTRACT_CANCEL' =>  ["ROLE_CONTRACT_CANCEL"],
    'ROLE_USER_DELETE' =>      ["ROLE_USER_DELETE"],
    'ROLE_CHEMSHEET_UPDATE' => ["ROLE_CHEMSHEET_UPDATE"],  # Editing a completed job on chemsheet page
    'ROLE_INVOICE_UPDATE' =>   ["ROLE_INVOICE_UPDATE"],  # Editing an invoice on payment details page
    'ROLE_INVOICE_CANCEL' =>   ["ROLE_INVOICE_CANCEL"],  # Cancelling an invoice on payment details page
    'ROLE_CUSTOMER_TRANSACTIONS' =>   ["ROLE_CUSTOMER_TRANSACTIONS"], # view transactions sidenav
    'ROLE_MESSAGE_SOMEONE' =>  ["ROLE_MESSAGE_SOMEONE"],  # Can Message Someone
    'ROLE_MESSAGE_TEAM' =>     ["ROLE_MESSAGE_SOMEONE"],  # Can message team
    'ROLE_MESSAGE_BRANCH' =>   ["ROLE_MESSAGE_TEAM"],  # Can message branch or office
    'ROLE_VTP_USER' =>             ["ROLE_VTP_USER"],
    'ROLE_QUICKBOOKS_SYNC' =>      ["ROLE_QUICKBOOKS_SYNC"],
    'ROLE_QUICKBOOKS_CONFIGURE' => ["ROLE_QUICKBOOKS_SYNC" ],
    'ROLE_WDO_TOOLS' =>        ["ROLE_WDO_TOOLS"], # WDO TOOLS ENABLE
    'ROLE_LEAD_ALERT' =>       ["ROLE_LEAD_ALERT"], # Alert on new leads from external source
    'ROLE_API' =>              ["ROLE_API"], # API User
    'ROLE_ONLINE_BOOKING' => ["ROLE_ONLINE_BOOKING"], #enabled Online Booking
    'ROLE_ALERT_ONLINE_BOOKING' => ["ROLE_ALERT_ONLINE_BOOKING"], #enable online booking alert

    # Access Matrix Roles
    'ROLE_ROUTE_VIEWADD' =>       ["ROLE_ROUTE_VIEW"],
    'ROLE_JOB_RESCHEDULE' =>      ["ROLE_JOB_RESCHEDULE"],
    'ROLE_JOB_CANCEL' =>          ["ROLE_JOB_CANCEL"],
    'ROLE_FULL_ACCOUNT_NUMBER' => ["ROLE_FULL_ACCOUNT_NUMBER"],
    'ROLE_SHOW_ALL_PINS_LEAD_MAP' => ["ROLE_SHOW_ALL_PINS_LEAD_MAP"],
    'ROLE_VTP_ADMIN' =>           ["ROLE_VTP_ADMIN"],
    'ROLE_GEO_CODE' =>            ["ROLE_GEO_CODE"],
    'ROLE_EDIT_CUSTOMER_ID' =>    ["ROLE_EDIT_CUSTOMER_ID"],
    'ROLE_RECRUIT_LINKER' =>      ["ROLE_RECRUIT_LINKER"],
    'ROLE_RECRUIT_DELETE' =>      ["ROLE_RECRUIT_DELETE"],
    'ROLE_TECH_RESTRICTED' =>     ["ROLE_TECH_RESTRICTED"],
    'ROLE_COMMISSION_REPORT' =>   ["ROLE_COMMISSION_REPORT"],
    'ROLE_ACCOUNT_NOTES' =>  ["ROLE_ACCOUNT_NOTES"],
    'ROLE_USER_VIEWADD' =>        ["ROLE_USER_WRITE"],

    # Message Board Roles
    'ROLE_TACKBOARD_ALERTS' =>    ["ROLE_TACKBOARD_ALERTS"],
    'ROLE_TACKBOARD_TODOS' =>     ["ROLE_TACKBOARD_TODOS"],
    'ROLE_TACKBOARD_NOTES' =>     ["ROLE_TACKBOARD_NOTES"],
    'ROLE_TACKBOARD_HISTORY' =>   ["ROLE_TACKBOARD_HISTORY"],

    # Ability to access any user's leads
    'ROLE_LEAD_ADMIN' =>       ["ROLE_LEAD_WRITE"],

    # Access to the sales tracker, "but" not necessarily a salesperson
    'ROLE_SALESTRACKER' =>    ["ROLE_COMPANY_RECORD_READ" ],

    # Menu Roles
    'ROLE_HIDE_SETTING' => ["ROLE_HIDE_SETTING"],
    'ROLE_HIDE_REPORTS' => ["ROLE_HIDE_REPORTS"],
    'ROLE_HIDE_FINANCIAL' => ["ROLE_HIDE_FINANCIAL"],
    'ROLE_HIDE_SALES_TRACKER' => ["ROLE_HIDE_SALES_TRACKER"],
    'ROLE_HIDE_VTP' => ["ROLE_HIDE_VTP"],

    # Access to management areas of sales tracker, "but" not necessarily a sales manager
    'ROLE_SALESTRACKER_MANAGER' => ["ROLE_SALESTRACKER", "ROLE_COMPANY_RECORD_WRITE" ],

    'ROLE_INVENTORY_WRITE' => ["ROLE_INVENTORY_READ", "ROLE_DISTRIBUTOR_WRITE", "ROLE_PRODUCT_WRITE", "ROLE_VEHICLE_WRITE", "ROLE_RECRUIT_OFFICE_WRITE" ],
    'ROLE_INVENTORY_READ' =>  ["ROLE_PRODUCT_READ", "ROLE_VEHICLE_READ", "ROLE_DISTRIBUTOR_READ" ],
    'ROLE_SETTINGS_WRITE' =>  ["ROLE_SETTINGS_READ", "ROLE_PEST_WRITE", "ROLE_SERVICE_WRITE", "ROLE_AREA_WRITE", "ROLE_TAG_WRITE", "ROLE_PESTCONFIG_WRITE", "ROLE_SERVICETYPE_WRITE", "ROLE_COUNTY_WRITE" ],
    'ROLE_SETTINGS_READ' =>   ["ROLE_PEST_READ", "ROLE_SERVICE_READ", "ROLE_AREA_READ", "ROLE_TAG_READ", "ROLE_PESTCONFIG_READ", "ROLE_SERVICETYPE_READ", "ROLE_COUNTY_READ" ],
    'ROLE_SETTINGS_SMS_WRITE' => ["ROLE_SETTINGS_SMS_READ"],
    'ROLE_TACKBOARD_READ' =>  ["ROLE_TACKBOARD_WRITE" ],

    'ROLE_ADMIN' =>           ["ROLE_OWNER", "ROLE_ALLOWED_TO_SWITCH", "ROLE_RECRUIT_MASTER_CONFIG_WRITE", "ROLE_COMPANY_WRITE" ],

    'ROLE_OWNER' =>           ["ROLE_BRANCH_MANAGER", "ROLE_MOVE_JOBS_TO_PAST", "ROLE_USER_DELETE", "ROLE_USER_WRITE", "ROLE_RECRUIT_DELETE", "ROLE_ZIPCODES_EDIT" ],
    'ROLE_BRANCH_MANAGER' =>  ["ROLE_SECRETARY", "ROLE_SALES_STATUS_WRITE", "ROLE_OFFICE_WRITE", "ROLE_REPORT_CONTRACT", "ROLE_REPORT_COMPARISON", "ROLE_ROUTE_BULK_COMPLETE", "ROLE_SALES_ALERT_CONFIG_WRITE", "ROLE_REPORT_SUMMER_TOTAL", "ROLE_QUICKBOOKS_CONFIGURE", "ROLE_MESSAGE_EVERYONE", "ROLE_CHANGE_SERVICE_PRICE" ],
    'ROLE_SECRETARY' =>       ["ROLE_OFFICE_USER", "ROLE_SALESTRACKER_MANAGER", "ROLE_COMMISSION_REPORT", "ROLE_AGREEMENT_WRITE", "ROLE_CUSTOMER_WRITE", "ROLE_ROUTE_WRITE", "ROLE_INVENTORY_WRITE", "ROLE_DASHBOARD_WRITE", "ROLE_SETTINGS_WRITE", "ROLE_INVOICE_REFUND", "ROLE_TACKBOARD_READ", "ROLE_MAPS_READ", "ROLE_CONTRACT_CANCEL", "ROLE_CHEMSHEET_UPDATE", "ROLE_INVOICE_UPDATE", "ROLE_INVOICE_CANCEL", "ROLE_CUSTOMER_TRANSACTIONS", "ROLE_CUSTOMFIELD_WRITE", "ROLE_LEAD_ADMIN", "ROLE_ACCOUNT_WRITE", "ROLE_CUSTOMER_ACTIONS", "ROLE_RECRUIT_WRITE", "ROLE_RECRUIT_CONFIG_WRITE", "ROLE_SETTINGS_SMS_WRITE", "ROLE_PHONE_WRITE", "ROLE_QR_CODE_BATCH_WRITE", "ROLE_QR_CODE_SCAN_WRITE", "ROLE_PAYMENT_BULK", "ROLE_QUICKBOOKS_SYNC", "ROLE_BULK_COLLECTIONS", "ROLE_ROUTE_BULK_CONFIRM", "ROLE_STATUS_REASON_WRITE", "ROLE_HISTORY_READ", "ROLE_TAXCODES_EDIT", "ROLE_CHANGE_SERVICE_PRICE" ],

    'ROLE_TECHNICIAN' =>      ["ROLE_OFFICE_USER", "ROLE_AGREEMENT_READ", "ROLE_CUSTOMER_WRITE", "ROLE_INVENTORY_READ", "ROLE_PRODUCT_WRITE", "ROLE_TACKBOARD_READ", "ROLE_MAPS_READ", "ROLE_JOB_COMPLETE", "ROLE_ROUTE_BULK_COMPLETE", "ROLE_INVOICE_UPDATE", "ROLE_ROUTE_PROCESS", "ROLE_ACCOUNT_CREATE", "ROLE_CUSTOMER_ACTIONS", "ROLE_QR_CODE_SCAN_WRITE", "ROLE_VTP_USER" ],

    'ROLE_SALESPERSON' =>     ["ROLE_OFFICE_USER", "ROLE_SALESTRACKER", "ROLE_AGREEMENT_READ", "ROLE_CUSTOMER_CREATE", "ROLE_TACKBOARD_READ", "ROLE_MAPS_READ", "ROLE_DASHBOARD_READ", "ROLE_REPORT_COMPARISON_DATA", "ROLE_TEAM_MESSAGE_WRITE", "ROLE_PERSONAL_MESSAGE_WRITE", "ROLE_COMPANY_RECORD_READ", "ROLE_LEAD_WRITE", "ROLE_REPORT_COMPARISON", "ROLE_VTP_USER", "ROLE_ACCOUNT_NOTES" ],
    'ROLE_SALES_MANAGER' =>   ["ROLE_SALESTRACKER_MANAGER", "ROLE_SALESPERSON", "ROLE_COMMISSION_REPORT", "ROLE_SETTINGS_WRITE", "ROLE_SETTINGS_SMS_WRITE", "ROLE_AGREEMENT_WRITE", "ROLE_OFFICE_WRITE", "ROLE_OFFICE_MESSAGE_WRITE", "ROLE_CUSTOMER_WRITE", "ROLE_CONTRACT_CANCEL" ],
    'ROLE_ROUTE_MANAGER' =>   ["ROLE_SALES_MANAGER", "ROLE_SALESTRACKER_MANAGER", "ROLE_REPORT_COMPARISON" ],
    'ROLE_SALES_ADMIN' =>     ["ROLE_SALES_MANAGER", "ROLE_OWNER", "ROLE_COMPANY_MESSAGE_WRITE", "ROLE_ROUTE_PROCESS", "ROLE_COMPANY_RECORD_WRITE", "ROLE_JOB_COMPLETE", "ROLE_SALES_ALERT_CONFIG_WRITE", "ROLE_LEAD_ADMIN", "ROLE_MESSAGE_BRANCH" ],

    'ROLE_COLLECTIONS' =>     ["ROLE_USER", "ROLE_CUSTOMER_WRITE", "ROLE_TACKBOARD_READ", "ROLE_MESSAGE_SOMEONE", "ROLE_ACCOUNT_NOTES" ],

    'ROLE_OFFICE_USER' =>     ["ROLE_USER", "ROLE_MESSAGE_SOMEONE", "ROLE_MESSAGE_TEAM", "ROLE_MESSAGE_BRANCH" ],

    'ROLE_CUSTOMER' =>        ["ROLE_USER" ]
];
